Algoritmo "semnome"
// 
//  

Var
codigo, qndte, soma: real


Inicio
escreval ("Informe o código do produto: ")
leia (codigo)

escreval ("Informe a quantidade comprada:")
leia (qntde)

se (codigo = 1001) entao
soma <- (qntde * 5.32)

escreval ("Produto do código",codigo,)
senao
se (codigo = 1324) entao
soma <- (qntde * 6.45)

escreval (codigo = 6548)
soma <- (qntde * 2.37)

escreval ("O total é: ", soma)
senao
se (codigo = 987) entao
Fimalgoritmo