Algoritmo "semnome"

Var
// Seção de Declarações das variáveis 
i: inteiro
vetA: vetor[1..5] de inteiro
vetB: vetor[1..5] de inteiro
vetC: vetor[1..5] de inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval ("Informe um valor para o 1 vetor: ")
leia (vetA[5])

escreval ("Informe um valor para o 2 vetor: ")
leia (vetB[5])

vetC[5] <- vetB[5] + vetA [5]
escreval ("A soma do 1 vetor + 2 vetor = vetor 3 e: ", vetC[5])
Fimalgoritmo